name: Churn Model Training

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/iterative/cml:latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt --no-cache-dir

      - name: Train model
        run: python script.py

      - name: Check if conf_matrix exists
        run: |
          ls -la
          test -f conf_matrix.png

      - name: Set release tag
        run: echo "TAG=release-$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ env.TAG }}
          name: Release ${{ env.TAG }}
          body: "Release created automatically from push."

      - name: Upload Confusion Matrix
        uses: softprops/action-gh-release@v1
        with:
          files: conf_matrix.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
