name: Churn Model Training

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/iterative/cml:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y python3-dev build-essential

      - name: Upgrade pip & install dependencies
        run: |
          python --version
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Train model
        run: |
          python script.py

      - name: Publish metrics and plots
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create --publish conf_matrix.png < metrics.txt
